// See use sfml::window::Key
use sfml::window::Key::*;
// pub const sfKeyCode_sfKeyUnknown: sfKeyCode = -1;
// pub const sfKeyCode_sfKeyA: sfKeyCode = 0;
// pub const sfKeyCode_sfKeyB: sfKeyCode = 1;
// pub const sfKeyCode_sfKeyC: sfKeyCode = 2;
// pub const sfKeyCode_sfKeyD: sfKeyCode = 3;
// pub const sfKeyCode_sfKeyE: sfKeyCode = 4;
// pub const sfKeyCode_sfKeyF: sfKeyCode = 5;
// pub const sfKeyCode_sfKeyG: sfKeyCode = 6;
// pub const sfKeyCode_sfKeyH: sfKeyCode = 7;
// pub const sfKeyCode_sfKeyI: sfKeyCode = 8;
// pub const sfKeyCode_sfKeyJ: sfKeyCode = 9;
// pub const sfKeyCode_sfKeyK: sfKeyCode = 10;
// pub const sfKeyCode_sfKeyL: sfKeyCode = 11;
// pub const sfKeyCode_sfKeyM: sfKeyCode = 12;
// pub const sfKeyCode_sfKeyN: sfKeyCode = 13;
// pub const sfKeyCode_sfKeyO: sfKeyCode = 14;
// pub const sfKeyCode_sfKeyP: sfKeyCode = 15;
// pub const sfKeyCode_sfKeyQ: sfKeyCode = 16;
// pub const sfKeyCode_sfKeyR: sfKeyCode = 17;
// pub const sfKeyCode_sfKeyS: sfKeyCode = 18;
// pub const sfKeyCode_sfKeyT: sfKeyCode = 19;
// pub const sfKeyCode_sfKeyU: sfKeyCode = 20;
// pub const sfKeyCode_sfKeyV: sfKeyCode = 21;
// pub const sfKeyCode_sfKeyW: sfKeyCode = 22;
// pub const sfKeyCode_sfKeyX: sfKeyCode = 23;
// pub const sfKeyCode_sfKeyY: sfKeyCode = 24;
// pub const sfKeyCode_sfKeyZ: sfKeyCode = 25;
// pub const sfKeyCode_sfKeyNum0: sfKeyCode = 26;
// pub const sfKeyCode_sfKeyNum1: sfKeyCode = 27;
// pub const sfKeyCode_sfKeyNum2: sfKeyCode = 28;
// pub const sfKeyCode_sfKeyNum3: sfKeyCode = 29;
// pub const sfKeyCode_sfKeyNum4: sfKeyCode = 30;
// pub const sfKeyCode_sfKeyNum5: sfKeyCode = 31;
// pub const sfKeyCode_sfKeyNum6: sfKeyCode = 32;
// pub const sfKeyCode_sfKeyNum7: sfKeyCode = 33;
// pub const sfKeyCode_sfKeyNum8: sfKeyCode = 34;
// pub const sfKeyCode_sfKeyNum9: sfKeyCode = 35;
// pub const sfKeyCode_sfKeyEscape: sfKeyCode = 36;
// pub const sfKeyCode_sfKeyLControl: sfKeyCode = 37;
// pub const sfKeyCode_sfKeyLShift: sfKeyCode = 38;
// pub const sfKeyCode_sfKeyLAlt: sfKeyCode = 39;
// pub const sfKeyCode_sfKeyLSystem: sfKeyCode = 40;
// pub const sfKeyCode_sfKeyRControl: sfKeyCode = 41;
// pub const sfKeyCode_sfKeyRShift: sfKeyCode = 42;
// pub const sfKeyCode_sfKeyRAlt: sfKeyCode = 43;
// pub const sfKeyCode_sfKeyRSystem: sfKeyCode = 44;
// pub const sfKeyCode_sfKeyMenu: sfKeyCode = 45;
// pub const sfKeyCode_sfKeyLBracket: sfKeyCode = 46;
// pub const sfKeyCode_sfKeyRBracket: sfKeyCode = 47;
// pub const sfKeyCode_sfKeySemicolon: sfKeyCode = 48;
// pub const sfKeyCode_sfKeyComma: sfKeyCode = 49;
// pub const sfKeyCode_sfKeyPeriod: sfKeyCode = 50;
// pub const sfKeyCode_sfKeyQuote: sfKeyCode = 51;
// pub const sfKeyCode_sfKeySlash: sfKeyCode = 52;
// pub const sfKeyCode_sfKeyBackslash: sfKeyCode = 53;
// pub const sfKeyCode_sfKeyTilde: sfKeyCode = 54;
// pub const sfKeyCode_sfKeyEqual: sfKeyCode = 55;
// pub const sfKeyCode_sfKeyHyphen: sfKeyCode = 56;
// pub const sfKeyCode_sfKeySpace: sfKeyCode = 57;
// pub const sfKeyCode_sfKeyEnter: sfKeyCode = 58;
// pub const sfKeyCode_sfKeyBackspace: sfKeyCode = 59;
// pub const sfKeyCode_sfKeyTab: sfKeyCode = 60;
// pub const sfKeyCode_sfKeyPageUp: sfKeyCode = 61;
// pub const sfKeyCode_sfKeyPageDown: sfKeyCode = 62;
// pub const sfKeyCode_sfKeyEnd: sfKeyCode = 63;
// pub const sfKeyCode_sfKeyHome: sfKeyCode = 64;
// pub const sfKeyCode_sfKeyInsert: sfKeyCode = 65;
// pub const sfKeyCode_sfKeyDelete: sfKeyCode = 66;
// pub const sfKeyCode_sfKeyAdd: sfKeyCode = 67;
// pub const sfKeyCode_sfKeySubtract: sfKeyCode = 68;
// pub const sfKeyCode_sfKeyMultiply: sfKeyCode = 69;
// pub const sfKeyCode_sfKeyDivide: sfKeyCode = 70;
// pub const sfKeyCode_sfKeyLeft: sfKeyCode = 71;
// pub const sfKeyCode_sfKeyRight: sfKeyCode = 72;
// pub const sfKeyCode_sfKeyUp: sfKeyCode = 73;
// pub const sfKeyCode_sfKeyDown: sfKeyCode = 74;
// pub const sfKeyCode_sfKeyNumpad0: sfKeyCode = 75;
// pub const sfKeyCode_sfKeyNumpad1: sfKeyCode = 76;
// pub const sfKeyCode_sfKeyNumpad2: sfKeyCode = 77;
// pub const sfKeyCode_sfKeyNumpad3: sfKeyCode = 78;
// pub const sfKeyCode_sfKeyNumpad4: sfKeyCode = 79;
// pub const sfKeyCode_sfKeyNumpad5: sfKeyCode = 80;
// pub const sfKeyCode_sfKeyNumpad6: sfKeyCode = 81;
// pub const sfKeyCode_sfKeyNumpad7: sfKeyCode = 82;
// pub const sfKeyCode_sfKeyNumpad8: sfKeyCode = 83;
// pub const sfKeyCode_sfKeyNumpad9: sfKeyCode = 84;
// pub const sfKeyCode_sfKeyF1: sfKeyCode = 85;
// pub const sfKeyCode_sfKeyF2: sfKeyCode = 86;
// pub const sfKeyCode_sfKeyF3: sfKeyCode = 87;
// pub const sfKeyCode_sfKeyF4: sfKeyCode = 88;
// pub const sfKeyCode_sfKeyF5: sfKeyCode = 89;
// pub const sfKeyCode_sfKeyF6: sfKeyCode = 90;
// pub const sfKeyCode_sfKeyF7: sfKeyCode = 91;
// pub const sfKeyCode_sfKeyF8: sfKeyCode = 92;
// pub const sfKeyCode_sfKeyF9: sfKeyCode = 93;
// pub const sfKeyCode_sfKeyF10: sfKeyCode = 94;
// pub const sfKeyCode_sfKeyF11: sfKeyCode = 95;
// pub const sfKeyCode_sfKeyF12: sfKeyCode = 96;
// pub const sfKeyCode_sfKeyF13: sfKeyCode = 97;
// pub const sfKeyCode_sfKeyF14: sfKeyCode = 98;
// pub const sfKeyCode_sfKeyF15: sfKeyCode = 99;
// pub const sfKeyCode_sfKeyPause: sfKeyCode = 100;
// pub const sfKeyCode_sfKeyCount: sfKeyCode = 101;
// pub const sfKeyCode_sfKeyDash: sfKeyCode = 56;
// pub const sfKeyCode_sfKeyBack: sfKeyCode = 59;
// pub const sfKeyCode_sfKeyBackSlash: sfKeyCode = 53;
// pub const sfKeyCode_sfKeySemiColon: sfKeyCode = 48;
// pub const sfKeyCode_sfKeyReturn: sfKeyCode = 58;

enum Keys {
    Unknown = -1,
    A = 0,
    B = 1,
    C = 2,
    D = 3,
    E = 4,
    F = 5,
    G = 6,
    H = 7,
    I = 8,
    J = 9,
    K = 10,
    L = 11,
    M = 12,
    N = 13,
    O = 14,
    P = 15,
    Q = 16,
    R = 17,
    S = 18,
    T = 19,
    U = 20,
    V = 21,
    W = 22,
    X = 23,
    Y = 24,
    Z = 25,
    Num0 = 26,
    Num1 = 27,
    Num2 = 28,
    Num3 = 29,
    Num4 = 30,
    Num5 = 31,
    Num6 = 32,
    Num7 = 33,
    Num8 = 34,
    Num9 = 35,
    Escape = 36,
    LeftControl = 37,
    LeftShift = 38,
    LeftAlt = 39,
    /// The left windows key
    LeftSuper = 40,
    RightControl = 41,
    RightShift = 42,
    RightAlt = 43,
    /// The right windows key. Only some keyboards have this.
    RightSuper = 44,
    Menu = 45,
    LeftBracket = 46,
    RightBracket = 47,
    Semicolon = 48,
    Comma =  49,
    Period = 50,
    Quote = 51,
    Slash = 52,
    Backslash= 53,
    Tilde= 54,
    Equal = 55,
    Hyphen= 56,
    Space = 57,
    Enter = 58,
    Backspace = 59,
    Tab= 60,
    PageUp = 61,
    PageDown = 62,
    End = 63,
    Home = 64,
    Insert = 65,
    Delete = 66,
    Add = 67,
    Subtract = 68,
    Multiply = 69,
    Divide = 70,
    Left = 71,
    Right = 72,
    Up = 73,
    Down = 74,
    Numpad0 = 75,
    Numpad1 = 76,
    Numpad2 = 77,
    Numpad3 = 78,
    Numpad4 = 79,
    Numpad5 = 80,
    Numpad6 = 81,
    Numpad7 = 82,
    Numpad8 = 83,
    Numpad9 = 84,
    F1 = 85,
    F2 = 86,
    F3 = 87,
    F4 = 88,
    F5 = 89,
    F6 = 90,
    F7 = 91,
    F8 = 92,
    F9 = 93,
    F10 = 94,
    F11 = 95,
    F12 = 96,
    F13 = 97,
    F14 = 98,
    F15 = 99,
    Pause = 100,
    /// Number of keys
    Count = 101,
}



